name: Infrastructure CI/CD

on:
  push:
    branches: [ main, dev ]
    paths: [ 'nps-infra/**' ]
  pull_request:
    branches: [ main, dev ]
    paths: [ 'nps-infra/**' ]

env:
  NODE_VERSION: '18'
  AWS_REGION: 'us-east-1'

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: nps-infra/package-lock.json

    - name: Install dependencies
      working-directory: ./nps-infra
      run: npm ci

    - name: Validate Serverless configuration
      working-directory: ./nps-infra
      run: npx serverless config validate

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: '1.5.0'

    - name: Terraform Format Check
      working-directory: ./nps-infra/terraform
      run: terraform fmt -check

    - name: Terraform Init
      working-directory: ./nps-infra/terraform
      run: terraform init

    - name: Terraform Validate
      working-directory: ./nps-infra/terraform
      run: terraform validate

  plan:
    needs: validate
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: nps-infra/package-lock.json

    - name: Install dependencies
      working-directory: ./nps-infra
      run: npm ci

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: '1.5.0'

    - name: Terraform Init
      working-directory: ./nps-infra/terraform
      run: terraform init

    - name: Terraform Plan
      working-directory: ./nps-infra/terraform
      run: terraform plan -var-file="terraform.tfvars" -out=tfplan
      env:
        TF_VAR_jwt_secret: ${{ secrets.JWT_SECRET }}
        TF_VAR_zendesk_api_token: ${{ secrets.ZENDESK_API_TOKEN }}
        TF_VAR_zendesk_subdomain: ${{ secrets.ZENDESK_SUBDOMAIN }}
        TF_VAR_sunco_api_token: ${{ secrets.SUNCO_API_TOKEN }}

    - name: Upload Terraform Plan
      uses: actions/upload-artifact@v3
      with:
        name: terraform-plan
        path: nps-infra/terraform/tfplan

  deploy-dev:
    if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
    needs: validate
    runs-on: ubuntu-latest
    environment: development
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: nps-infra/package-lock.json

    - name: Install dependencies
      working-directory: ./nps-infra
      run: npm ci

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Deploy infrastructure to development
      working-directory: ./nps-infra
      run: npm run deploy:dev
      env:
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        ZENDESK_API_TOKEN: ${{ secrets.ZENDESK_API_TOKEN }}
        ZENDESK_SUBDOMAIN: ${{ secrets.ZENDESK_SUBDOMAIN }}
        SUNCO_API_TOKEN: ${{ secrets.SUNCO_API_TOKEN }}

  deploy-prod:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: validate
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: nps-infra/package-lock.json

    - name: Install dependencies
      working-directory: ./nps-infra
      run: npm ci

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Deploy infrastructure to production
      working-directory: ./nps-infra
      run: npm run deploy:prod
      env:
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        ZENDESK_API_TOKEN: ${{ secrets.ZENDESK_API_TOKEN }}
        ZENDESK_SUBDOMAIN: ${{ secrets.ZENDESK_SUBDOMAIN }}
        SUNCO_API_TOKEN: ${{ secrets.SUNCO_API_TOKEN }}
